site_name: Hardware Lab Guide
nav:
    - Home: index.md
    - Verilog: verilog_main.md
    - MIPS: mips_main.md
    - About Us: about.md
theme:
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: teal

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: blue grey
    
  logo: img/favicon.ico 
  name: material
  favicon: img/favicon.ico  
  features:
    - navigation.tabs
    - navigation.footer
    # - navigation.tabs.sticky
    - toc.integrate
extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/hwlabnitc
  homepage: https://minerva.nitc.ac.in/ 

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
